import { Link } from "react-router";
import { PublicFooter, PublicHeader } from "../components/PublicChrome";

type PageProps={path:string;eyebrow:string;title:string;intro:string;children:React.ReactNode};
function Page({path,eyebrow,title,intro,children}:PageProps){return <div className="pm-info"><PublicHeader activePath={path}/><main id="main-content"><section className="pm-info-hero"><span>{eyebrow}</span><h1>{title}</h1><p>{intro}</p></section>{children}</main><PublicFooter/></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="pm-info-section"><h2>{title}</h2>{children}</section>}
export function AboutRoute(){return <Page path="/about" eyebrow="About ProofMode" title="Practice the decisions AI cannot own." intro="ProofMode is an agentic-coding game about directing AI, checking evidence, and deciding what should ship."><Section title="Why we made it"><p>AI makes building faster, but confidence is not proof. We turn real mistakes, contradictions, and recoveries into short practice you can repeat.</p><div className="pm-info-grid"><article><b>Direct</b><p>Give the agent a precise objective and boundaries.</p></article><article><b>Verify</b><p>Compare claims with requirements, tests, and behavior.</p></article><article><b>Decide</b><p>Lock a call you can explain and defend.</p></article></div></Section></Page>}
export function GuideRoute(){return <Page path="/guide" eyebrow="How it works" title="Your first mission, without the guesswork." intro="A mission is a compact loop: read, direct, inspect, challenge, lock, and replay."><Section title="The six-stage loop"><ol className="pm-steps">{["Read the contract","Direct the agent","Inspect the work","Challenge the claim","Lock the decision","Replay the proof"].map((x,i)=><li key={x}><span>0{i+1}</span><b>{x}</b></li>)}</ol><Link className="pm-info-action" to="/play">Try today’s mission →</Link></Section></Page>}
export function PremiumRoute(){return <Page path="/premium" eyebrow="Premium direction" title="Pay for depth—not artificial limits." intro="Premium is planned, not on sale. Pricing and payments are not live."><Section title="What may earn a subscription"><div className="pm-info-grid"><article><b>Advanced missions</b><p>Longer production scenarios and specialist paths.</p></article><article><b>Deeper replay</b><p>Extended history, comparison, and practice insight.</p></article><article><b>Never pay to win</b><p>Rank, wins, and scoring advantage will not be sold.</p></article></div></Section></Page>}
export function SupportRoute(){return <Page path="/support" eyebrow="Support and feedback" title="Get unstuck. Tell us what failed." intro="ProofMode is in private pre-alpha. Support systems are still being built."><Section title="How to help"><div className="pm-info-grid"><article><b>Bug report</b><p>Describe what you expected, what happened, and your device.</p></article><article><b>Product feedback</b><p>Tell us which moment felt unclear or unhelpful.</p></article><article><b>Safety</b><p>Do not include passwords, API keys, or private code.</p></article></div><p className="pm-honesty">This preview does not send or store a message yet.</p></Section></Page>}
export function DownloadRoute(){return <Page path="/download" eyebrow="Access ProofMode" title="Start in the browser. Native apps are next." intro="The web app is available now. Signed native installers and updates are future work."><Section title="Available now"><Link className="pm-info-action" to="/play">Open ProofMode web app ↗</Link></Section><Section title="Planned desktop installers"><div className="pm-download-grid"><article><span>Windows</span><button disabled>Windows installer · Coming later</button></article><article><span>macOS</span><button disabled>macOS installer · Coming later</button></article></div><ol className="pm-update-flow"><li>Download the signed installer for your system.</li><li>Install and open ProofMode normally.</li><li>The app shows “Update available” for a verified release.</li><li>You confirm before the supported updater installs it.</li></ol><p className="pm-honesty">No native installer exists today. Never bypass an operating-system warning.</p></Section></Page>}
